config/routes.rb
Rails.application.routes.draw do
	devise_for :user, controllers: { registrations: 'user/registrations' }
	
  resources :categories do
  	resources :courses do
  		resources :lessons
  		patch 'lessons/:id/activate', to: 'lessons#activate', as: 'activate_lesson'
      post 'lessons/:id/add_to_basket', to: 'lessons#add_to_basket', as: 'add_to_basket'
      post 'lessons/:id/buy', to: 'lessons#buy', as: 'buy_lesson'
      delete 'lessons/:id/delete_from_cart', to: 'lessons#delete_from_basket', as: 'delete_from_basket'
  	end

  	patch 'courses/:id/activate', to: 'courses#activate', as: 'activate_course'
  end

  get 'teacher_courses/', to: 'courses#teacher_courses', as: 'teacher_courses'
  get 'cart/', to: 'baskets#index', as: 'cart'
  get 'paid_lessons/', to: 'paid_lessons#index', as: 'paid_lessons'
  get 'checks/', to: 'checks#index', as: 'checks'
  post 'cart/buy_lessons', to: 'baskets#buy', as: 'buy_lessons'
  resources :users, except: [:new, :create]
  patch 'users/:id/block', to: 'users#block', as: 'block_user'
  patch 'users/:id/unblock', to: 'users#unblock', as: 'unblock_user'

  root to: 'categories#index' 
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :courses, dependent: :delete_all
	validates :name, presence: true, length: { maximum: 100 }
	validates :description, length: { maximum: 500 }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :first_interlocutor
  belongs_to :second_interlocutor
end

app/models/chat_visit.rb
class ChatVisit < ApplicationRecord
  belongs_to :chat
end

app/models/check.rb
class Check < ApplicationRecord
	enum currency: [:KGS, :RUB, :USD, :EUR]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :category
  has_many :lessons, dependent: :delete_all
  
  validates :name, presence: true, length: { maximum: 100 }
	validates :description, length: { maximum: 500 }
end

app/models/done_homework.rb
class DoneHomework < ApplicationRecord
  belongs_to :teacher
  belongs_to :homework
  belongs_to :client
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :manager
end

app/models/file_homework.rb
class FileHomework < ApplicationRecord
  belongs_to :homework
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :lesson
end

app/models/homework_code.rb
class HomeworkCode < ApplicationRecord
  belongs_to :homework
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_one_attached :video
  has_many_attached :files
  
  enum currency: [:KGS, :RUB, :USD, :EUR]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender
  belongs_to :chat
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :lesson
  belongs_to :basket
end

app/models/paid_lesson.rb
class PaidLesson < ApplicationRecord
  belongs_to :check
  belongs_to :user
  belongs_to :lesson
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :basket, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:admin, :client, :manager, :superuser, :teacher]

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def has_subscription?
    self.subscription
  end

  def rights
    if self.superuser?
      "Superuser"
    elsif self.admin?
      "Admin"
    elsif self.client?
      "Client"
    elsif self.manager?
      "Manager"
    elsif self.teacher?
      "Teacher"
    end
  end
end

app/models/word_homework.rb
class WordHomework < ApplicationRecord
  belongs_to :homework
end

app/controllers/user/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  def create
    super
    Basket.create(user: @user)
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :email, :subscription, :role])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :email, :subscription, :role])
  end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit block unblock update destroy ]
  
  def index
  	check_superuser_rights do
      @users = User.all.order :id
	  end
  end

  def show
  end

  def edit
  end

  def block
    @user.blocked = true
    @user.save
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully blocked." }
    end
  end

  def unblock
    @user.blocked = false
    @user.save
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully unblocked." }
    end
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
    end
  end

  private

    def set_user
      check_superuser_rights do
        @user = User.find(params[:id])
      end
    end

  	def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :subscription, :blocked, :role)
    end

    def check_superuser_rights
      if user_signed_in? and current_user.superuser?
        yield
      else
        redirect_to categories_url, status: :found, alert: "You don't have enough rights"
      end
    end
end

app/helpers/checks_helper.rb
module ChecksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Rights:</strong>
  <%= @user.rights %>
</p>

<p>
  <strong>Subscription:</strong>
  <%= @user.has_subscription? %>
</p>

<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @user.updated_at %>
</p>

<%= form_with(model: @user) do |form| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>

      <ul>
        <% @user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :role %>
    <%= form.select :role, User.roles.keys.map { |w| [w.humanize, w] } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Edit Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/users/index.html.erb
<h1>Users</h1>

<table>
  <thead>
  	<tr>
  		<th>#</th>
      <th>First</th>
      <th>Last</th>
      <th>Email</th>
      <th>Subscription?</th>
      <th>Blocked?</th>
      <th colspan="3">Actions</th>
      <th>Destroy</th>
    </tr>
  </thead>

  <tbody>
	  <% @users.each do |user| %>
	  	<tr class="line">
	  		<td><%= user.id %></td>
	  		<td><%= user.first_name %></td>
	  		<td><%= user.last_name %></td>
	  		<td><%= user.email %></td>
	  		<% if user.client? %>
	  			<td class="subscription <%= user.has_subscription? %>"><%= user.has_subscription? %></td>
	  		<% else %>
	  			<td class="role">Is <%= user.rights %></td>
	  		<% end %>
	  		<td class="blocked <%= user.blocked %>"><%= user.blocked %></td>
	  		<td><%= link_to 'Show', user %></td>
	  		<td><%= link_to 'Edit', edit_user_path(user) %></td>
	  		<% if !user.blocked %>
	  			<td><%= link_to 'Block', block_user_path(user), method: :patch, data: { confirm: 'Are you sure you want to block user?' }%></td>
	  		<% else %>
	  			<td><%= link_to 'Unblock', unblock_user_path(user), method: :patch, data: { confirm: 'Are you sure you want to unblock user?' } %></td>
	  		<% end %>
	  		<td><%= link_to 'Destroy', user, class: 'destroy', method: :delete, data: { confirm: 'Are you sure?' } %></td>
	  	</tr>
	  <% end %>
	</tbody>
</table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Rights:</strong>
  <%= @user.rights %>
</p>

<% if @user.client? %>
	<p>
	  <strong>Subscription:</strong>
	  <%= @user.has_subscription? %>
	</p>
<% end %>

<p>
  <strong>Created at:</strong>
  <%= @user.created_at %>
</p>

<p>
  <strong>Updated at:</strong>
  <%= @user.updated_at %>
</p>

<details>
    <summary>Sign in data</summary>
    <p>
	  <strong>Last sign in ip:</strong>
	  <%= @user.last_sign_in_ip %>
	</p>

	<p>
	  <strong>Current sign in ip:</strong>
	  <%= @user.current_sign_in_ip %>
	</p>

	<p>
	  <strong>Current sign in at:</strong>
	  <%= @user.current_sign_in_at %>
	</p>

	<p>
	  <strong>Sign in count:</strong>
	  <%= @user.sign_in_count %>
	</p>

	<p>
	  <strong>Remember created at:</strong>
	  <%= @user.remember_created_at %>
	</p>

</details>


<details>
	<summary>Password data</summary>
	<p>
	  <strong>Encrypted password:</strong>
	  <%= @user.encrypted_password %>
	</p>

	<p>
	  <strong>Reset password token:</strong>
	  <%= @user.reset_password_token %>
	</p>

	<p>
	  <strong>Reset password sent at:</strong>
	  <%= @user.reset_password_sent_at %>
	</p>
</details>

<details>
	<summary>Confirmation data:</summary>
	<p>
	  <strong>Confirmation token:</strong>
	  <%= @user.confirmation_token %>
	</p>

	<p>
	  <strong>Confirmed at:</strong>
	  <%= @user.confirmed_at %>
	</p>

	<p>
	  <strong>Confirmation sent at:</strong>
	  <%= @user.confirmation_sent_at %>
	</p>
</details>

<details>
	<summary>Lock data:</summary>
	<p>
	  <strong>Unlock token:</strong>
	  <%= @user.unlock_token %>
	</p>

	<p>
	  <strong>Locked at:</strong>
	  <%= @user.locked_at %>
	</p>

	<p>
	  <strong>Blocked:</strong>
	  <%= @user.blocked %>
	</p>
</details>

<%= link_to 'Back', users_path %>