config/routes.rb
Rails.application.routes.draw do
	devise_for :user, controllers: { registrations: 'user/registrations' }
	
  resources :categories do
  	resources :courses do
  		resources :lessons
  		patch 'lessons/:id/activate', to: 'lessons#activate', as: 'activate_lesson'
      post 'lessons/:id/add_to_basket', to: 'lessons#add_to_basket', as: 'add_to_basket'
      post 'lessons/:id/buy', to: 'lessons#buy', as: 'buy_lesson'
      delete 'lessons/:id/delete_from_cart', to: 'lessons#delete_from_basket', as: 'delete_from_basket'
  	end

  	patch 'courses/:id/activate', to: 'courses#activate', as: 'activate_course'
  end

  get 'teacher_courses/', to: 'courses#teacher_courses', as: 'teacher_courses'
  get 'cart/', to: 'baskets#index', as: 'cart'
  get 'paid_lessons/', to: 'paid_lessons#index', as: 'paid_lessons'
  get 'checks/', to: 'checks#index', as: 'checks'
  post 'cart/buy_lessons', to: 'baskets#buy', as: 'buy_lessons'
  resources :users, except: [:new, :create]
  patch 'users/:id/block', to: 'users#block', as: 'block_user'
  patch 'users/:id/unblock', to: 'users#unblock', as: 'unblock_user'

  root to: 'categories#index' 
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_one_attached :video
  has_many_attached :files
  
  enum currency: [:KGS, :RUB, :USD, :EUR]
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
	before_action :set_lesson, only: %i[ show edit update destroy ]

  def index
    course = Course.find(params[:course_id])
  	if check_superuser_rights
  		@lessons = course.lessons
      @course = course
    elsif check_teacher_rights and course.teacher_id == current_user.id
      @lessons = course.lessons
      @course = course
  	else
  		@lessons = course.lessons.where active: true
      @course = course
  	end
  end

  def show
  end

  def new
  	@lesson = Course.find(params[:course_id]).lessons.build
  end

  def edit
  end

  def create
  	@lesson = Course.find(params[:course_id]).lessons.build(lessons_params)
    if @lesson.free == true
      @lesson.price = 0
    end
  	respond_to do |format|
      if @lesson.save
        format.html { redirect_to category_course_lesson_path(@lesson.course.category_id, @lesson.course_id, @lesson), notice: "Lesson was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
	  end
  end

  def update
  	respond_to do |format|
      if @lesson.update(lessons_params)
        format.html { redirect_to category_course_lesson_path(@lesson.course.category_id, @lesson.course_id, @lesson), notice: "Lesson was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @lesson.video.purge
    @lesson.files.purge
  	@lesson.destroy
    respond_to do |format|
      format.html { redirect_to category_course_lessons_path, notice: "Lesson was successfully destroyed." }
    end
  end

  def activate
  	if user_signed_in? and (current_user.superuser? or current_user.teacher?)
      lesson = Course.find(params[:course_id]).lessons.find(params[:id])
      if lesson.course.teacher_id == current_user.id or current_user.superuser?
        lesson.active == true ? lesson.active = false : lesson.active = true
        lesson.save
        respond_to do |format|
          format.html { redirect_to category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), notice: "Lesson was successfully activated." }
        end
      else
        redirect_to category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), status: :found, alert: "You don't have enough rights"
      end
    end
  end

  def add_to_basket
    if check_client_rights
      lesson = Course.find(params[:course_id]).lessons.find(params[:id])
      if PaidLesson.where(lesson: lesson, user: current_user).empty?
        if current_user.basket.orders.where(lesson: lesson).empty?
          Order.create(lesson: lesson, basket: current_user.basket)
          respond_to do |format|
            format.html { redirect_to category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), notice: "Lesson was successfully added to cart." }
          end
        else
          redirect_to category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), status: :found, alert: "You already added this lesson to cart"
        end
      else
        redirect_to category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), status: :found, alert: "You already bought this lesson"
      end
    end
  end

  def delete_from_basket
    if check_client_rights
      lesson = Course.find(params[:course_id]).lessons.find(params[:id])
      order = current_user.basket.orders.where(lesson: lesson)
      if !order.empty?
        order.first.destroy
        respond_to do |format|
          format.html { redirect_to cart_path, notice: "Lesson was successfully deleted from cart." }
        end
      else
        redirect_to category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), status: :found, alert: "Nothing to delete from cart"
      end
    end
  end

  def buy
    if check_client_rights
      lesson = Course.find(params[:course_id]).lessons.find(params[:id])
      if PaidLesson.where(lesson: lesson, user: current_user).empty?
        check = Check.create(sum: lesson.price, customer: SecureRandom.hex(16))
        paid_lesson = PaidLesson.create(check: check, lesson: lesson, user: current_user)
        respond_to do |format|
            format.html { redirect_to category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), notice: "Lesson was successfully bought." }
          end
      else
        redirect_to category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), status: :found, alert: "You already bought this lesson"
      end
    end
  end

  private

  	def set_lesson
      lesson = Course.find(params[:course_id]).lessons.find(params[:id])
      if check_active(lesson) or check_superuser_rights or (check_teacher_rights and lesson.course.teacher_id == current_user.id)
      	@lesson = lesson
      else
      	redirect_to category_course_lessons_url, status: :found
      end
    end

  	def lessons_params
      params.require(:lesson).permit(:course_id, :free, :name, :text, :price, :currency, :active, :video, files: [])
    end

    def check_active(lesson)
    	lesson.active and lesson.course.active
    end

    def check_superuser_rights
      user_signed_in? and current_user.superuser? ? true : false
    end

    def check_teacher_rights
    	user_signed_in? and current_user.teacher? ? true : false
    end

    def check_client_rights
    	user_signed_in? and current_user.client? ? true : false
    end

    def check_admin_rights
    	user_signed_in? and current_user.admin? ? true : false
    end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/_form.html.erb
<%= form_with(model: [@lesson.course.category, @lesson.course, @lesson]) do |form| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
        <% @lesson.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :free %>
    <%= form.check_box :free %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.number_field :price %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.select :currency, Lesson.currencies.keys.map { |w| [w, w] } %>
  </div>

  <div class="field">
    <%= form.label :video %>
    <%= form.file_field :video %>
  </div>

  <div class="field">
    <%= form.label :files %>
    <%= form.file_field :files, :multiple => true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Edit Lesson</h1>

<%= render 'form', laesson: @laesson %>

<%= link_to 'Back', category_course_lessons_path %>

app/views/lessons/index.html.erb
<h1>Lessons</h1>
<% if !@lessons.empty? %>
	<% @lessons.each do |lesson| %>
	<div>
		<p><%= lesson.name %></p>
		<%= link_to 'Show', category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson) %>
		<% if user_signed_in? and (current_user.superuser? or (current_user.teacher? and lesson.course.teacher_id == current_user.id)) %>
		    | <%= link_to 'Edit', edit_category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson) %> |
		    <%= link_to 'Destroy', category_course_lesson_path(lesson.course.category_id, lesson.course_id, lesson), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</div>
	<% end %>
<% else %>
	<p>Doesn't anything here</p>
<% end %>

<% if user_signed_in? and (current_user.superuser? or (current_user.teacher? and @course.teacher_id == current_user.id)) %>
	<p><%= link_to 'New lesson', new_category_course_lesson_path %></p>
<% end %>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form', lesson: @lesson %>

<%= link_to 'Back', category_course_lessons_path %>

app/views/lessons/show.html.erb
<p>
  <strong>Course:</strong>
  <%= @lesson.course.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lesson.name %>
</p>

<p>
  <strong>Free:</strong>
  <%= @lesson.free %>
</p>

<p>
  <strong>Text:</strong>
  <%= @lesson.text %>
</p>

<p>
  <strong>Price:</strong>
  <%= @lesson.price %> <%= @lesson.currency %>
</p>

<p>
  <strong>Active:</strong>
  <%= @lesson.active %>

  <% if user_signed_in? and (current_user.superuser? or @lesson.course.teacher_id == current_user.id) %>
	<% if !@lesson.active %>
		<%= link_to 'Activate', category_course_activate_lesson_path(@lesson), method: :patch, data: { confirm: 'Are you sure you want to activate lesson?' } %>
	<% elsif @lesson.active %>
		<%= link_to 'Deactivate', category_course_activate_lesson_path(@lesson), method: :patch, data: { confirm: 'Are you sure you want to deactivate lesson?' } %>
	<% end %>
<% end %>
</p>

<% if @lesson.video.attached? %>
  <%= video_tag url_for(@lesson.video), size: "320x240", controls: true %> <br>
<% end %>

<details>
  <summary>Files</summary>
  <% @lesson.files.each do |file| %>
    <p>
      <%= link_to file.filename ,rails_blob_path(file, disposition: "attachment") %>
    </p>
  <% end %>

</details>

<%= link_to 'Add to cart', category_course_add_to_basket_path(@lesson), method: :post %>
<%= link_to 'Buy', category_course_buy_lesson_path(@lesson), method: :post %>

<% if user_signed_in? and current_user.superuser? %>
	<%= link_to 'Edit', edit_category_course_lesson_path(@lesson.course.category_id, @lesson.course_id, @lesson) %> |
<% end %>
<%= link_to 'Back', category_course_lessons_path(@lesson.course.category_id, @lesson.course_id) %>