config/routes.rb
Rails.application.routes.draw do
	devise_for :user, controllers: { registrations: 'user/registrations' }
	
  resources :categories do
  	resources :courses do
  		resources :lessons
  		patch 'lessons/:id/activate', to: 'lessons#activate', as: 'activate_lesson'
      post 'lessons/:id/add_to_basket', to: 'lessons#add_to_basket', as: 'add_to_basket'
      post 'lessons/:id/buy', to: 'lessons#buy', as: 'buy_lesson'
      delete 'lessons/:id/delete_from_cart', to: 'lessons#delete_from_basket', as: 'delete_from_basket'
  	end

  	patch 'courses/:id/activate', to: 'courses#activate', as: 'activate_course'
  end

  get 'teacher_courses/', to: 'courses#teacher_courses', as: 'teacher_courses'
  get 'cart/', to: 'baskets#index', as: 'cart'
  get 'paid_lessons/', to: 'paid_lessons#index', as: 'paid_lessons'
  get 'checks/', to: 'checks#index', as: 'checks'
  post 'cart/buy_lessons', to: 'baskets#buy', as: 'buy_lessons'
  resources :users, except: [:new, :create]
  patch 'users/:id/block', to: 'users#block', as: 'block_user'
  patch 'users/:id/unblock', to: 'users#unblock', as: 'unblock_user'

  root to: 'categories#index' 
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :courses, dependent: :delete_all
	validates :name, presence: true, length: { maximum: 100 }
	validates :description, length: { maximum: 500 }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :first_interlocutor
  belongs_to :second_interlocutor
end

app/models/chat_visit.rb
class ChatVisit < ApplicationRecord
  belongs_to :chat
end

app/models/check.rb
class Check < ApplicationRecord
	enum currency: [:KGS, :RUB, :USD, :EUR]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :category
  has_many :lessons, dependent: :delete_all
  
  validates :name, presence: true, length: { maximum: 100 }
	validates :description, length: { maximum: 500 }
end

app/models/done_homework.rb
class DoneHomework < ApplicationRecord
  belongs_to :teacher
  belongs_to :homework
  belongs_to :client
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :manager
end

app/models/file_homework.rb
class FileHomework < ApplicationRecord
  belongs_to :homework
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :lesson
end

app/models/homework_code.rb
class HomeworkCode < ApplicationRecord
  belongs_to :homework
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_one_attached :video
  has_many_attached :files
  
  enum currency: [:KGS, :RUB, :USD, :EUR]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender
  belongs_to :chat
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :lesson
  belongs_to :basket
end

app/models/paid_lesson.rb
class PaidLesson < ApplicationRecord
  belongs_to :check
  belongs_to :user
  belongs_to :lesson
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :basket, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:admin, :client, :manager, :superuser, :teacher]

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def has_subscription?
    self.subscription
  end

  def rights
    if self.superuser?
      "Superuser"
    elsif self.admin?
      "Admin"
    elsif self.client?
      "Client"
    elsif self.manager?
      "Manager"
    elsif self.teacher?
      "Teacher"
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ edit update destroy ]
	before_action :authenticate_user!, except: %i[ index show ]

  def index
    if user_signed_in? and current_user.superuser?
  	  @courses = Category.find(params[:category_id]).courses
      @category_id = params[:category_id]
    elsif user_signed_in? and current_user.teacher?
      @courses = Category.find(params[:category_id]).courses.where(teacher_id: current_user.id)
      @category_id = params[:category_id]
    else
      @courses = Category.find(params[:category_id]).courses.where(active: true)
      @category_id = params[:category_id]
    end
  end

  def teacher_courses
    if current_user.teacher?
      @courses = Course.where(teacher_id: current_user.id)
      @category_id = params[:category_id]
    else
      redirect_to courses_url, status: :found, alert: "You are not a teacher"
    end
  end

  def show
  	course = Category.find(params[:category_id]).courses.find(params[:id])
    if course.active?
      @course = course 
    elsif user_signed_in? and (current_user.superuser? or current_user.teacher?)
      if course.teacher_id == current_user.id or current_user.superuser?
        @course = course
      end
    else
      redirect_to category_courses_url(course.category_id), status: :not_found, alert: "Not found"
    end
  end

  def new
  	if user_signed_in? and (current_user.superuser? or current_user.teacher?)
  		@course = Category.find(params[:category_id]).courses.build
	  end
  end

  def edit
  end

  def create
  	if user_signed_in? and (current_user.superuser? or current_user.teacher?)
	  	@course = Category.find(params[:category_id]).courses.build(courses_params)
      if current_user.teacher?
        @course.teacher = current_user
      end

	  	respond_to do |format|
	      if @course.save
	        format.html { redirect_to category_course_path(@course.category_id, @course), notice: "Course was successfully created." }
	      else
	        format.html { render :new, status: :unprocessable_entity }
	      end
	    end
	  end
  end

  def update
  	respond_to do |format|
      if @course.update(courses_params)
        format.html { redirect_to category_course_path(@course.category_id, @course), notice: "Course was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to category_courses_url(course.category_id), notice: "Course was successfully destroyed." }
    end
  end

  def activate
    if user_signed_in? and (current_user.superuser? or current_user.teacher?)
      course = Category.find(params[:category_id]).courses.find(params[:id])
      if course.teacher_id == current_user.id or current_user.superuser?
        course.active == true ? course.active = false : course.active = true
        course.save
        respond_to do |format|
          format.html { redirect_to category_course_path(course.category_id, course), notice: "Course was successfully activated." }
        end
      else
        redirect_to category_courses_url(course.category_id), status: :found, alert: "You don't have enough rights"
      end
    end
  end

  private

	  def set_course
	  	if user_signed_in? and (current_user.superuser? or current_user.teacher?)
	    	course = Category.find(params[:category_id]).courses.find(params[:id])
        if course.teacher_id == current_user.id or current_user.superuser?
          @course = course
        else
          redirect_to category_courses_url(course.category_id), status: :found, alert: "You don't have enough rights"
        end
		  end
	  end

  	def courses_params
      params.require(:course).permit(:category_id, :name, :description, :active, :teacher_id)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: [@course.category, @course]) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :teacher %>
    <%= form.select :teacher_id, options_for_select(User.where(role: :teacher).map{|s|[s.full_name, s.id]}) %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Edit Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', category_courses_path %>

app/views/courses/index.html.erb
<h1>Courses</h1>
<% if !@courses.empty? %>
	<% @courses.each do |course| %>
	<div>
		<p><%= course.name %></p>
		<%= link_to 'Show', category_course_path(course.category_id, course) %>
		<% if user_signed_in? and current_user.superuser? %>
		    | <%= link_to 'Edit', edit_category_course_path(course.category_id, course) %> |
		    <%= link_to 'Destroy', category_course_path(course.category_id, course), method: :delete, data: { confirm: 'Are you sure?' } %>
		<% end %>
	</div>
	<% end %>
<% else %>
	<p>Doesn't anything here</p>
<% end %>

<% if (user_signed_in? and current_user.superuser?) or (user_signed_in? and current_user.teacher?) %>
	<p><%= link_to 'New course', new_category_course_path(@category_id) %></p>
<% end %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', category_courses_path %>

app/views/courses/show.html.erb
<p>
  <strong>Category:</strong>
  <%= @course.category.name %>
</p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= User.find(@course.teacher_id).full_name %>
</p>

<p>
  <strong>Active:</strong>
  <%= @course.active %>

  <% if user_signed_in? and (current_user.superuser? or @course.teacher_id == current_user.id) %>
	<% if !@course.active %>
		<%= link_to 'Activate', category_activate_course_path(@course.category_id, @course), method: :patch, data: { confirm: 'Are you sure you want to activate course?' } %>
	<% elsif @course.active %>
		<%= link_to 'Deactivate', category_activate_course_path(@course.category_id, @course), method: :patch, data: { confirm: 'Are you sure you want to deactivate course?' } %>
	<% end %>
<% end %>
</p>

<% if user_signed_in? and current_user.superuser? %>
	<%= link_to 'Edit', edit_category_course_path(@course.category_id, @course) %> |
<% end %>
<%= link_to 'Back', category_courses_path %>

app/views/courses/teacher_courses.html.erb
<h1>Courses</h1>
<% if !@courses.empty? %>
	<% @courses.each do |course| %>
	<div>
		<p><%= course.name %></p>
		<%= link_to 'Show', category_course_path(course.category_id, course) %>
		| <%= link_to 'Edit', edit_category_course_path(course.category_id, course) %> |
		<%= link_to 'Destroy', category_course_path(course.category_id, course), method: :delete, data: { confirm: 'Are you sure?' } %>
	</div>
	<% end %>
<% else %>
	<p>Doesn't anything here</p>
<% end %>

<p><%= link_to 'New course', new_category_course_path(@category_id) %></p>