config/routes.rb
Rails.application.routes.draw do
	devise_for :user, controllers: { registrations: 'user/registrations' }
	
  resources :categories do
  	resources :courses do
  		resources :lessons
  		patch 'lessons/:id/activate', to: 'lessons#activate', as: 'activate_lesson'
      post 'lessons/:id/add_to_basket', to: 'lessons#add_to_basket', as: 'add_to_basket'
      post 'lessons/:id/buy', to: 'lessons#buy', as: 'buy_lesson'
      delete 'lessons/:id/delete_from_cart', to: 'lessons#delete_from_basket', as: 'delete_from_basket'
  	end

  	patch 'courses/:id/activate', to: 'courses#activate', as: 'activate_course'
  end

  get 'teacher_courses/', to: 'courses#teacher_courses', as: 'teacher_courses'
  get 'cart/', to: 'baskets#index', as: 'cart'
  get 'paid_lessons/', to: 'paid_lessons#index', as: 'paid_lessons'
  get 'checks/', to: 'checks#index', as: 'checks'
  post 'cart/buy_lessons', to: 'baskets#buy', as: 'buy_lessons'
  resources :users, except: [:new, :create]
  patch 'users/:id/block', to: 'users#block', as: 'block_user'
  patch 'users/:id/unblock', to: 'users#unblock', as: 'unblock_user'

  root to: 'categories#index' 
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  belongs_to :user
end

app/models/basket.rb
class Basket < ApplicationRecord
  belongs_to :user
  has_many :orders, dependent: :destroy
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :courses, dependent: :delete_all
	validates :name, presence: true, length: { maximum: 100 }
	validates :description, length: { maximum: 500 }
end

app/models/chat.rb
class Chat < ApplicationRecord
  belongs_to :first_interlocutor
  belongs_to :second_interlocutor
end

app/models/chat_visit.rb
class ChatVisit < ApplicationRecord
  belongs_to :chat
end

app/models/check.rb
class Check < ApplicationRecord
	enum currency: [:KGS, :RUB, :USD, :EUR]
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :category
  has_many :lessons, dependent: :delete_all
  
  validates :name, presence: true, length: { maximum: 100 }
	validates :description, length: { maximum: 500 }
end

app/models/done_homework.rb
class DoneHomework < ApplicationRecord
  belongs_to :teacher
  belongs_to :homework
  belongs_to :client
end

app/models/email.rb
class Email < ApplicationRecord
  belongs_to :manager
end

app/models/file_homework.rb
class FileHomework < ApplicationRecord
  belongs_to :homework
end

app/models/homework.rb
class Homework < ApplicationRecord
  belongs_to :lesson
end

app/models/homework_code.rb
class HomeworkCode < ApplicationRecord
  belongs_to :homework
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_one_attached :video
  has_many_attached :files
  
  enum currency: [:KGS, :RUB, :USD, :EUR]
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender
  belongs_to :chat
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :lesson
  belongs_to :basket
end

app/models/paid_lesson.rb
class PaidLesson < ApplicationRecord
  belongs_to :check
  belongs_to :user
  belongs_to :lesson
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_one :basket, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:admin, :client, :manager, :superuser, :teacher]

  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def has_subscription?
    self.subscription
  end

  def rights
    if self.superuser?
      "Superuser"
    elsif self.admin?
      "Admin"
    elsif self.client?
      "Client"
    elsif self.manager?
      "Manager"
    elsif self.teacher?
      "Teacher"
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineCourse</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p id="notice"><%= notice %></p>
    <p id="alert"><%= alert %></p>

    <% if user_signed_in? %>
      <p><%= current_user.email %></p>
      <% if current_user.teacher? %> 
        <%= link_to 'Your courses', teacher_courses_path %>
      <% end %>
      <%= link_to 'Sign out', destroy_user_session_path, method: :delete %> | 
      <%= link_to 'Cart', cart_path %> |
      <%= link_to 'Paid lessons', paid_lessons_path %> |
      <%= link_to 'Checks', checks_path %>
    <% else %>
      <%= link_to 'Sign in', new_user_session_path %>
      <%= link_to 'Sign up', new_user_registration_path %>
    <% end %>
    <%= yield %>
  </body>
</html>